# Generated by Django 3.2.5 on 2021-07-07 13:00

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20210707_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
        migrations.RemoveField(
            model_name='images',
            name='author',
        ),
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
        migrations.RemoveField(
            model_name='images',
            name='date',
        ),
        migrations.RemoveField(
            model_name='images',
            name='description',
        ),
        migrations.RemoveField(
            model_name='images',
            name='location',
        ),
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
